# Generated by Django 5.1 on 2024-08-31 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0002_profile_phone'),
        ('shop', '0016_alter_product_slug_alter_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='shop.product')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_user.profile')),
            ],
        ),
    ]
