# Generated by Django 5.1 on 2024-09-02 13:43

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_profile_phone'),
        ('delivery_staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='profile',
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ManyToManyField(to='auth_user.profile'),
        ),
    ]
