# Generated by Django 5.1 on 2024-09-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_profile_phone'),
        ('delivery_staff', '0002_alter_order_managers_remove_order_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profile',
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_user.profile'),
        ),
    ]
