# Generated by Django 5.1 on 2024-08-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to='images', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
