# Generated by Django 5.1 on 2024-09-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_created=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.TextField(choices=[('1', 'Sale'), ('2', 'News'), ('3', 'Text')], null=True, verbose_name='Тип'),
        ),
    ]
