# Generated by Django 5.1 on 2024-09-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_date_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
