# Generated by Django 5.1 on 2024-08-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(default='images/default.png', upload_to='images/subcat', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='animalsort',
            name='subcategory',
            field=models.ManyToManyField(to='shop.subcategory', verbose_name='Подкатегории'),
        ),
    ]
