# Generated by Django 5.1 on 2024-08-18 10:49

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
        ('shop', '0004_basket'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='feedback',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='author',
        ),
        migrations.AddField(
            model_name='feedback',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_user.profile'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(to='shop.product'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(max_length=1000, null=True, verbose_name='Отзыв'),
        ),
    ]
