# Generated by Django 5.1 on 2024-08-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_feedback_managers_remove_feedback_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='img',
            field=models.ImageField(default='images/default.png', upload_to='images/provider', verbose_name='Фото'),
        ),
    ]
