# Generated by Django 5.1 on 2024-08-18 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_provider_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
