# Generated by Django 5.1 on 2024-08-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_feedback_products'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='feedback',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='bought',
            field=models.ManyToManyField(to='shop.product'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(related_name='shop_basket_product', to='shop.product'),
        ),
    ]
