# Generated by Django 5.1 on 2024-08-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_feedback_managers_basket_bought_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(max_length=1000, null=True, verbose_name='Отзыв'),
        ),
    ]
