# Generated by Django 5.1 on 2024-08-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_feedback_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shortdescription',
            field=models.CharField(max_length=100, null=True, verbose_name='Краткое описание'),
        ),
    ]
