# Generated by Django 5.1 on 2024-08-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalsort',
            name='slug',
            field=models.SlugField(default='slug', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='slug', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
