# Generated by Django 5.1 on 2024-08-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
        ('shop', '0011_animalsort_slug_category_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_user.profile'),
        ),
    ]
