# Generated by Django 5.1 on 2024-08-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_feedback_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='img',
        ),
    ]
