# Generated by Django 5.1 on 2024-08-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default=False, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
